name: SSUSA
favicon: null
layout_spectrum: 0.6984417526982725
typography_spectrum: 0.7534299090038985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4012893084436655
  lightness: 0.7197423372417688
  saturation: 0.9541863391641527
  rhythmicContrast: 0.8926537099760026
purpose: []
